const BOOKS = [
  {
    id: 1,
    title: "Python Crash Course",
    author: "Eric Matthes",
    category: "programming",
    difficulty: "beginner",
    available: true,
    featured: true,
    description:
      "Python Crash Course is the world s bestselling programming book, with over 1,500,000 copies sold to date!Since its initial debut in 2015, this critically acclaimed quick-start guide to programming has taught millions of people all over the world to write clean code, solve problems, and build custom applications in the popular language of Python. The highly anticipated third edition of Python Crash Course has been completely revised with updated code, practices, and projects making it the ultimate launchpad for beginners to start their engines and code in Python 3!In addition to detailed step-by-step instructions, illustrated explanations of code snippets, and fun, hands-on exercises that lock in learning, the new edition features enhanced coverage of variables, error-handling, and object-oriented programming, as well as fresh data for each chapter s coding projects, better app deployment, and the latest libraries and tools, such as Plotly, Django, and the Tailwind CSS framework.As you go from software installation tutorials and language-navigation basics to mastering syntax and troubleshooting, you ll develop a solid programming foundation for the book s increasingly complex array of projects. Create responsive 2D games, design your own web apps, and even generate interactive visualisations all while you pick up and practice clean, universally applicable programming skills!",
    cover: "/images/thumbnails/programming-cover-small.jpg",
  },
  {
    id: 2,
    title: "Fluent Python",
    author: "Luciano Ramalho",
    category: "programming",
    difficulty: "advanced",
    available: false,
    featured: true,
    description:
      "Don't waste time bending Python to fit patterns you've learned in other languages. Python's simplicity lets you become productive quickly, but often this means you aren't using everything the language has to offer. With the updated edition of this hands-on guide, you'll learn how to write effective, modern Python 3 code by leveraging its best ideas. Discover and apply idiomatic Python 3 features beyond your past experience. Author Luciano Ramalho guides you through Python's core language features and libraries and teaches you how to make your code shorter, faster, and more readable.",
    cover: "/images/thumbnails/cover-17.jpg",
  },
  {
    id: 3,
    title: "Computer Networking: A Top-Down Approach",
    author: "James F. Kurose, Keith W. Ross",
    category: "networks",
    difficulty: "intermediate",
    available: true,
    featured: true,
    description:
      "Unique among computer networking texts, the Seventh Edition of the popular Computer Networking: A Top Down Approach builds on the author’s long tradition of teaching this complex subject through a layered approach in a “top-down manner.” The text works its way from the application layer down toward the physical layer, motivating readers by exposing them to important concepts early in their study of networking. Focusing on the Internet and the fundamentally important issues of networking, this text provides an excellent foundation for readers interested in computer science and electrical engineering, without requiring extensive knowledge of programming or mathematics. The Seventh Edition has been updated to reflect the most important and exciting recent advances in networking.",
    cover: "/images/thumbnails/networks-cover-3.avif",
  },
  {
    id: 4,
    title: "Cybersecurity Essentials",
    author: "Charles J. Brooks et al.",
    category: "cybersecurity",
    difficulty: "beginner",
    available: true,
    featured: true,
    description:
      "Cybersecurity Essentials provides a comprehensive introduction to the field, with expert coverage of essential topics required for entry-level cybersecurity certifications. An effective defense consists of four distinct challenges: securing the infrastructure, securing devices, securing local networks, and securing the perimeter. Overcoming these challenges requires a detailed understanding of the concepts and practices within each realm. This book covers each challenge individually for greater depth of information, with real-world scenarios that show what vulnerabilities look like in everyday computing scenarios. Each part concludes with a summary of key concepts, review questions, and hands-on exercises, allowing you to test your understanding while exercising your new critical skills. Cybersecurity jobs range from basic configuration to advanced systems analysis and defense assessment. This book provides the foundational information you need to understand the basics of the field, identify your place within it, and start down the security certification path.",
    cover: "/images/thumbnails/cybersec-cover-3.jpg",
  },
  {
    id: 5,
    title: "SQL for Data Analysis",
    author: "Cathy Tanimura",
    category: "databases",
    difficulty: "intermediate",
    available: true,
    featured: false,
    description:
      "Learn how to query relational databases using SQL. Covers SELECT, JOIN, GROUP BY, window functions, subqueries, and practical data analysis workflows.",
    cover: "/images/thumbnails/databases-cover-5.jpg",
  },
  {
    id: 6,
    title: "Database System Concepts",
    author: "Abraham Silberschatz",
    category: "databases",
    difficulty: "intermediate",
    available: true,
    featured: false,
    description:
      "It presents the fundamental concepts of database management in an intuitive manner geared toward allowing students to begin working with databases as quickly as possible.",
    cover: "/images/thumbnails/databases-cover-5.jpg",
  },
  {
    id: 7,
    title: "Automate the Boring Stuff with Python",
    author: "Al Sweigart",
    category: "programming",
    difficulty: "beginner",
    available: true,
    featured: true,
    description:
      "Practical Python for everyday tasks: files, web scraping, Excel, PDFs, and automation projects for beginners.",
    cover: "/images/thumbnails/cover-25.jpg",
  },
  {
    id: 8,
    title: "Clean Code",
    author: "Robert C. Martin",
    category: "programming",
    difficulty: "intermediate",
    available: true,
    featured: false,
    description:
      "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn't have to be that way. Noted software expert Robert C. Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship. Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code 'on the fly' into a book that will instill within you the values of a software craftsman and make you a better programmer-but only if you work at it. What kind of work will you be doing? You'll be reading code-lots of code. And you will be challenged to think about what's right about that code, and what's wrong with it. More importantly, you will be challenged to reassess your professional values and your commitment to your craft. Clean Code is divided into three parts. The first describes the principles, patterns, and practices of writing clean code. The second part consists of several case studies of increasing complexity. Each case study is an exercise in cleaning up code-of transforming a code base that has some problems into one that is sound and efficient. The third part is the payoff: a single chapter containing a list of heuristics and 'smells' gathered while creating the case studies. The result is a knowledge base that describes the way we think when we write, read, and clean code. Readers will come away from this book understanding How to tell the difference between good and bad code How to write good code and how to transform bad code into good code How to create good names, good functions, good objects, and good classes How to format code for maximum readability How to implement complete error handling without obscuring code logic How to unit test and practice test-driven development This book is a must for any developer, software engineer, project manager, team lead, or systems analyst with an interest in producing better code.",
    cover: "/images/thumbnails/cover-28.jpg",
  },
  {
    id: 9,
    title: "Effective Java",
    author: "Joshua Bloch",
    category: "programming",
    difficulty: "advanced",
    available: true,
    featured: false,
    description:
      "Since this Jolt-award winning classic was last updated in 2008, the Java programming environment has changed dramatically. Java 7 and Java 8 introduced new features and functions including, forEach() method in Iterable interface, default and static methods in Interfaces, Functional Interfaces and Lambda Expressions, Java Stream API for Bulk Data Operations on Collections, Java Time API, Collection API improvements, Concurrency API improvements, and Java IO improvements. In this new edition of Effective Java, Bloch explores new design patterns and language idioms that have been introduced since the second edition was released in 2008 shortly after Java SE6, including Lambda, streams, generics and collections, as well as selected Java 9 features. As in previous editions, each chapter consists of several 'items' presented in the form of a short, standalone essay that provides specific advice, insight into Java platform subtleties, and updated code examples. The comprehensive descriptions and explanations for each item illuminate what to do, what not to do, and why. Updated techniques and best practices on classic topics, including objects, classes, libraries, methods, and serialization How to avoid the traps and pitfalls of commonly misunderstood subtleties of the language Focus on the language and its most fundamental libraries: java.lang, java.util, and, to a lesser extent, java.util.concurrent and java.io",
    cover: "/images/thumbnails/cover-5.jpg",
  },
  {
    id: 10,
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen et al.",
    category: "programming",
    difficulty: "advanced",
    available: true,
    featured: false,
    description:
      "A new edition of the essential text and professional reference, with substantial new material on such topics as vEB trees, multithreaded algorithms, dynamic programming, and edge-based flow. Some books on algorithms are rigorous but incomplete; others cover masses of material but lack rigor. Introduction to Algorithms uniquely combines rigor and comprehensiveness. The book covers a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers. Each chapter is relatively self-contained and can be used as a unit of study. The algorithms are described in English and in a pseudocode designed to be readable by anyone who has done a little programming. The explanations have been kept elementary without sacrificing depth of coverage or mathematical rigor. The first edition became a widely used text in universities worldwide as well as the standard reference for professionals. The second edition featured new chapters on the role of algorithms, probabilistic analysis and randomized algorithms, and linear programming. The third edition has been revised and updated throughout. It includes two completely new chapters, on van Emde Boas trees and multithreaded algorithms, substantial additions to the chapter on recurrence (now called 'Divide-and-Conquer'), and an appendix on matrices. It features improved treatment of dynamic programming and greedy algorithms and a new notion of edge-based flow in the material on flow networks. Many new exercises and problems have been added for this edition. The international paperback edition is no longer available; the hardcover is available worldwide.",
    cover: "/images/thumbnails/js-cover-3.jpg",
  },
  {
    id: 11,
    title: "Computer Networks",
    author: "Andrew S. Tanenbaum, David J. Wetherall",
    category: "networks",
    difficulty: "intermediate",
    available: true,
    featured: true,
    description:
      "Unique among computer networking texts, the 8th Edition of the popular Computer Networking: A Top Down Approach builds on the authors’ long tradition of teaching this complex subject through a layered approach in a “top-down manner.” The text works its way from the application layer down toward the physical layer, motivating students by exposing them to important concepts early in their study of networking. Focusing on the Internet and the fundamentally important issues of networking, this text provides an excellent foundation for students in computer science and electrical engineering, without requiring extensive knowledge of programming or mathematics. The 8th Edition has been updated to reflect the most important and exciting recent advances in networking, including the importance of software-defined networking (SDN) and the rapid adoption of 4G/5G networks and the mobile applications they enable.",
    cover: "/images/thumbnails/networks-cover-4.jpg",
  },
  {
    id: 12,
    title: "Network Security Essentials",
    author: "William Stallings",
    category: "networks",
    difficulty: "intermediate",
    available: true,
    featured: false,
    description:
      "Security protocols and mechanisms across networks: cryptography, VPNs, authentication, and secure design.",
    cover: "/images/thumbnails/networks-cover-3.avif",
  },
  {
    id: 13,
    title: "The Web Application Hacker's Handbook",
    author: "Dafydd Stuttard, Marcus Pinto",
    category: "cybersecurity",
    difficulty: "advanced",
    available: false,
    featured: false,
    description:
      "In-depth guide to web security testing concepts, attack surfaces, and defensive thinking.",
    cover: "/images/thumbnails/cybersec-cover-2-small.jpg",
  },
  {
    id: 14,
    title: "Practical Malware Analysis",
    author: "Michael Sikorski, Andrew Honig",
    category: "cybersecurity",
    difficulty: "advanced",
    available: true,
    featured: false,
    description:
      "A hands-on introduction to understanding malicious software behavior and analysis workflows.",
    cover: "/images/thumbnails/cybersec-cover-2-small.jpg",
  },
  {
    id: 15,
    title: "Database System Concepts",
    author: "Abraham Silberschatz et al.",
    category: "databases",
    difficulty: "intermediate",
    available: true,
    featured: true,
    description:
      "Strong academic foundation in relational theory, transactions, indexing, and database architecture.",
    cover: "/images/thumbnails/cybersec-cover-1.jpeg",
  },
  {
    id: 16,
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    category: "databases",
    difficulty: "advanced",
    available: true,
    featured: true,
    description:
      "Modern view of scalable systems, data models, distributed storage, and reliability tradeoffs.",
    cover: "/images/thumbnails/databases-cover-5.jpg",
  },
  {
    id: 17,
    title: "Web Dev",
    author: "Bill Karwin",
    category: "web-development",
    difficulty: "intermediate",
    available: true,
    featured: false,
    description:
      "Common database and SQL mistakes with practical fixes for better schema and query design.",
    cover: "/images/thumbnails/cover-6.jpeg",
  },

  {
    id: 18,
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    category: "web-development",
    difficulty: "intermediate",
    available: true,
    featured: true,
    description:
      "A modern, hands-on guide to JavaScript and web programming. Covers core language concepts, the DOM, async patterns, and practical examples for building real web apps.",
    cover: "/images/thumbnails/cover-11.jpg",
  },
  {
    id: 19,
    title: "A Mind for Numbers: How to Excel at Math and Science",
    author: "Barbara Oakley",
    category: "ai",
    difficulty: "beginner",
    available: true,
    featured: false,
    description:
      "A practical guide to learning challenging technical subjects. Covers effective study habits, avoiding procrastination, building problem-solving intuition, and improving long-term retention—great for CS and engineering students.",
    cover: "/images/thumbnails/cat-ai-cover.jpeg",
  },
  {
    id: 20,
    title: "Artificial Intelligence: A Modern Approach",
    author: "Norvig & Russell",
    category: "ai",
    difficulty: "beginner",
    available: true,
    featured: false,
    description:
      "A comprehensive introduction to AI fundamentals, covering intelligent agents, search and planning, knowledge representation, probabilistic reasoning, machine learning, and ethical considerations. Widely used as a core textbook with clear examples and exercises.",
    cover: "/images/thumbnails/cover-13.jpg",
  },
];
module.exports= BOOKS;
